### ISSUE TITLE
"cutting into non-free mapping"

### ISSUE THREAD

**Issue by RuthgerD** [maharmstone/quibble#25] opened 2020-07-05 13:33 UTC
I'm trying this project to boot windows 10 with btrfs as root on real hardware,  unsure if this is even supported but I'm getting an error.  
The only odd thing out is that I'm using an unofficial minimal windows iso install to speed up installs etc.
```
ARC name is btrfs(1f9da0e7-7228-7753-373a-54e2e4a73f76).
Loaded ntoskrnl.exe fffffeoo 0000000.
Booting NT version 10.0.19041.172.
Loading NLS file c_1252.nls..
Loading NLS file c_437.nls.
Loading NLS file l_intl.nls.
Loading inf\errata.Inf.
Using tm.sys Instead of ext-ms-win-ntos-tm-11-1-0.dll.
Using clipsp.sys instead of ext-ms-win-ntos-clipsp-11-1-0.dll.

....

Loaded storufs.sys at fffff80802b98000.
Loaded Intel TA.sys at fffff80802baa000.
Loaded volume.sys at fffff80802bb5000.
Loaded Windows TrustedRT.sys at fffff80802bco000 
Loaded Windows Trusted Proxy.sys at fffff80802
Loaded crashdmp.sys at fffff80802be2000.
Loaded tm.sys at fffff 80802000000
Loaded MASHED.d11 at fffff80802c27000.
Loaded BOOTVID.dll at fffff 80802041000
Loaded clipsp.sys at fffff 80802040000
Loaded kdcom.dll at fffff80802d5f000.
Loaded cmimcext.sys at fffff80802d6d0oo.
Loaded werkernel.sys at fffff80802d7b000.
Loaded ntosext.sys at fffff80802d8c000.
Loaded CI.dll at fffff80802d98000.
Loaded msrpc.sys at fffff80802e79000.
Loaded WDFLDR.SYS at fffff80802edbo00.
Loaded SleepStudyHelper.sys at fffff80802eee000.
Loaded WppRecorder.sys at fffff80802ef dooo.
Loaded WMILIB.SYS at fffff80802f0e000.
Loaded CEA.sys at fffff80802f 1a000.
Loaded PCIIDEX.SYS at fffff80802f33000.
Loaded CLASSPNP.SYS at fffff80802f46000 .
Loaded storport.sys at fffff80802fb2000.
Loaded NETIO.SYS at fffff 80803062000
Loaded ataport.SYS at fffff808030f 2000.
Loaded fupkcint.sys at fffff 80803136000
ext-ms-win-ntos-ksr-11-1-1.dll not found in API set array.
ACPI table at 57d600c8 error - cutting into non-free mapping
```
<sub>(log made by googles' text scanner so not 100% correct)<sub>

**Comment by yurikoles** [comment] 2020-07-05 15:25
I see some ACPI error

I'm not sure is this related, but this issue reminds me problems that we see in hackintosh community, e.g. booting macOS on generic Intel and AMD PCs. The problem is that macOS implement limited set of ACPI, but some MoBo and laptop vendors also implement some proprietary Windows-only features. 

So hackintosh community developed a lot of tools for dumping, disassembling, patching and recompiling DSDT tables. Then we put them in corresponding place, that is then picked up by bootloader and used instead of table from BIOS.

The very same problem is also known in Linux world and GRUB supports loading custom DSDT tables.

So if I'm right, @maharmstone could you please implement loading of patched DSDT tables in quibble?

**Comment by RuthgerD** [comment] 2020-07-05 16:03
I'm not really knowledgeable on uefi and acpi but this laptop (hp envy x360 ryzen 3700u) boots linux (systemd-boot and grub) and windows (stock boot manager) just fine, although HP is notorious for having _bad_ acpi stuff, so unless those implement quirks for my laptop quibble should be able to boot windows right?  
  
Also the `ext-ms-win-ntos-ksr-11-1-1.dll not found in API set array.` is more concerning I think.

**Comment by nikp123** [comment] 2020-10-14 21:44
I get the same result under QEMU with the BIOS linked in the README. Not sure what's going on.

**Comment by maharmstone** [comment] 2020-10-18 17:33
I think this is probably fixed by https://github.com/maharmstone/quibble/commit/c657723480343cbeb056ee6d8284357a31d254a0.

**Closed by maharmstone** 2020-10-18 17:33 UTC

**Comment by 512yottabytes** [comment] 2021-08-17 11:59
Have the same issue.
```
[Host]
OS: Ubuntu 20.04 x86_64
Hypervisor: KVM + QEMU + LibVirt

[Guest]
OS: Windows 10 21H1 x86_64
EFI: OVMF_CODE64--seabios.fd
FS: BTRFS (converted fron NTFS via ntfs2btrfs
Quibble version: 20210111
```
